
spring:
  datasource:
    url: jdbc:h2:file:/opt/database/deutsche;MODE=MySQL;DB_CLOSE_DELAY=-1;IFEXISTS=TRUE;AUTO_RECONNECT=TRUE;
    driverClassName: org.h2.Driver
    username: sa
    password: pwd
    hikari.connection-test-query: SELECT 1
    auto-commit: false
  jpa:
    #      ddl-auto: validate, update, create, create-drop, none
    hibernate.ddl-auto:  none
    show-sql: false
    format-sql: true
    properties.hibernate.format_sql: true
    hibernate.naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  sql:
    init:
      mode: never
      platform: h2
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true

