
spring:
  datasource:

    #    schema: classpath:droptables.sql
    #    data: classpath:data-static.sql, classpath:data-bc-h2.sql, classpath:data-ge-h2.sql

    url: jdbc:h2:file:/opt/database/deutsche;MODE=MySQL;DB_CLOSE_DELAY=-1;IFEXISTS=TRUE;AUTO_RECONNECT=TRUE;
    #    ;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE;

    driverClassName: org.h2.Driver
    username: sa
    password: pwd
    hikari.connection-test-query: SELECT 1
    #    initialization-mode: always
    auto-commit: true
  jpa:
    #    dialect: org.h2.Driver
    #      ddl-auto: validate, update, create, create-drop, none
    hibernate.ddl-auto:  update
    #    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    format-sql: true
    #    use-sql-comments: true
    properties.hibernate.format_sql: true
    hibernate.naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  sql:
    init:
      mode: always
      platform: h2
      schema-locations: classpath:droptables.sql, classpath:schema-h2.sql
  #      data-locations: classpath:data.sql
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true

